### ISSUE TITLE
Items endpoint not being refreshed after new item insert

### ISSUE THREAD

**Issue by omelendrez** [omelendrez/axis-backend#52]
## Description
Inside course view, where a user can add/remove items and modules/descriptions, new added items do not show, while new added modules do

## Discovery
Frontend and backend code are the same (except, of course, for the endpoint names).

## To do
Identify the reason of this behavior, apply fix and then re-activate cache for both endpoints

**Comment by melendrez-dev** [comment]
The issue was happening because the there was cache implemented in `route` but not use of `next` in the `controller`.
